# Generated by Django 3.0.8 on 2020-07-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='datetime',
        ),
    ]
