# Generated by Django 3.0.8 on 2020-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_remove_article_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
