# Generated by Django 3.0.8 on 2020-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_auto_20200709_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
